name: 'CI'
on:
  push:
    branches:
      - '!feature/*'
      - 'hotfix/*'
      - '!release'
jobs:
  ci:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - name: 'Use Node.js 15.5'
        uses: 'actions/setup-node@v1'
        with:
          node-version: '15.5'
      - name: 'Check out repository'
        uses: 'actions/checkout@v2'
        with:
          fetch-depth: 0
      - name: 'Install dependencies'
        run: 'yarn install --frozen-lockfile'
      - name: 'Increase memory size'
        run: 'export NODE_OPTIONS="--max-old-space-size=7168"'
      - name: 'Test'
        run: 'yarn test-parallel'
